experiment_name: 'GNN_flat_v0'
task_name: HopperBulletEnv-v0
alg: PPO
policy: GnnPolicy

device: cuda:0

drop_body_nodes: True
use_sibling_relations: False

# ["action_per_controller", "pooled", "pooled_by_group", "flattened"]
policy_readout_mode: 'flattened'

gnn_for_values: False

learning_rate: 3.0e-5
total_timesteps: 1000000
n_steps: 1024
batch_size: 64
activation_fn: Tanh