experiment_name: 'GNN_hopper_flat_v2_10M_1'
task_name: HopperBulletEnv-v0
alg: PPO
policy: GnnPolicy_V2

device: cuda:0

drop_body_nodes: True
use_sibling_relations: False

# ["action_per_controller", "pooled", "pooled_by_group", "flattened"]
policy_readout_mode: 'flattened'

gnn_for_values: False

learning_rate: 3.0e-5
total_timesteps: 10000000
n_steps: 1024
batch_size: 64
activation_fn: Tanh

net_arch:
  input:
    - [Linear, 256]
    - [Linear, 256]
  propagate:
    - [NerveNetConv, 128]
    - [NerveNetConv, 128]
    - [NerveNetConv, 128]
    - [NerveNetConv, 128]
  policy:
    - [Linear, 256]
    - [Linear, 256]
  value:
    - [Linear, 256]
    - [Linear, 256]