experiment_name: MLP_S64_P64_V64_N1024_B64_lr3e-5_5M

task_name: AntBulletEnv-v0
alg: PPO
policy: MlpPolicy

device: cuda:0

learning_rate: !!float 3e-5
total_timesteps: 5000000
n_steps: 1024
batch_size: 64
activation_fn: ReLU


net_arch:
  - pi: [256, 256]
    vf: [256, 256]